
###
# @json 200 ok
POST http://localhost:5299/json
Content-Type: application/json

{
    "name": "myname"
}


###
# @json 400 badrequest
POST http://localhost:5299/json
Content-Type: application/json

{
    "undefined": "somevalue"
}



###
# @path 200 ok
GET http://localhost:5299/path/1


###
# @json 400 badrequest
GET http://localhost:5299/path/somename
