###
# @me
GET http://localhost:5299/auth/user/me


###
# @login
POST http://localhost:5299/auth/user/login
Content-Type: application/json

{
    "email": "admin@stardust.io",
    "password": "1qaz2wsx!"
}

###
# @create apikey

POST http://localhost:5299/auth/user/apikey
Content-Type: application/json

{
    "description" : "testsample"
}


# {
#   "code": 200,
#   "data": {
#     "id": 2,
#     "key": "53ce97cf782d4795953b1eb52801074f",
#     "description": "testsample"
#   }
# }

###
# @me
GET http://localhost:5299/auth/user/me
X-ApiKey : 53ce97cf782d4795953b1eb52801074f


###
# @get apikey

GET http://localhost:5299/auth/user/apikey
X-ApiKey : 53ce97cf782d4795953b1eb52801074f

###
# @delete apikey

DELETE http://localhost:5299/auth/user/apikey/1
X-ApiKey : 53ce97cf782d4795953b1eb52801074f