
###
# @me
GET http://localhost:5299/auth/user/me



###
# @login
POST http://localhost:5299/auth/user/login
Content-Type: application/json

{
    "email": "admin@stardust.io",
    "password": "1qaz2wsx!"
}

###
# @logout
POST http://localhost:5299/auth/user/logout



###
# @signup

POST http://localhost:5299/auth/user/signup
Content-Type: application/json

{
    "email": "test@stardust.io",
    "password": "1qaz2wsx!",
    "username": "test"
}

###
# @login
POST http://localhost:5299/auth/user/login
Content-Type: application/json

{
    "email": "test@stardust.io",
    "password": "1qaz2wsx!"
}
